service: spring-boot-serverless-api

provider:
  name: aws
  runtime: java11
  region: us-east-1
  memorySize: 512
  timeout: 30
  stackName: spring-boot-serverless-api-dev
  iam:
    role: ${env:AWS_ROLE}
  environment:
    SPRING_DATASOURCE_URL: ${env:SPRING_DATASOURCE_URL}
    SPRING_DATASOURCE_USERNAME: ${env:SPRING_DATASOURCE_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${env:SPRING_DATASOURCE_PASSWORD}


package:
  artifact: target/csw-0.0.1.jar

functions:
  api:
    handler: csw.t1.csw.LambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
