service: spring-boot-serverless-api

provider:
  name: aws
  runtime: java11
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    SPRING_DATASOURCE_URL: ${env:SPRING_DATASOURCE_URL}
    SPRING_DATASOURCE_USERNAME: ${env:SPRING_DATASOURCE_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${env:SPRING_DATASOURCE_PASSWORD}

package:
  artifact: build/libs/spring-boot-serverless-api-1.0.0.jar

functions:
  api:
    handler: csw.t1.csw.LambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
