service: spring-boot-serverless-api

provider:
  name: aws
  runtime: java21
  region: us-east-1
  stage: api
  timeout: 30
  memorySize: 512
  stackName: spring-boot-serverless-api-dev
  iam:
    role: arn:aws:iam::930082020931:role/LabRole
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://spring-boot-serverless-db-new.cqzes9oh1wgy.us-east-1.rds.amazonaws.com:5432/mydatabasee
    SPRING_DATASOURCE_USERNAME: csww
    SPRING_DATASOURCE_PASSWORD: password

package:
  artifact: target/csw-0.0.1.jar

functions:
  api:
    handler: csw.t1.csw.LambdaHandler::handleRequest
    events:
      - http:
          method: any
          path: /{proxy+}