name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurar o JDK 21 para compilar o projeto
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Especifica a distribuição OpenJDK
          java-version: '21'

      # Step 3: Build do projeto com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Zipar o JAR gerado para preparar para o Lambda
      - name: Zip application
        run: zip -j my-app.zip target/*.jar

      # Step 5: Instalar ou atualizar o AWS CLI
      - name: Install or update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      # Step 6: Deploy para o AWS Lambda usando AWS CLI
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Substitua pela sua região
        run: |
          aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://my-app.zip
