name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurar JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build do projeto com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Compactar o JAR em um arquivo ZIP para o Lambda
      - name: Zip application
        run: zip -j my-app.zip target/*.jar

      # Step 5: Instalar a AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Step 6: Deploy para AWS Lambda usando a AWS CLI
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://my-app.zip \
            --region us-east-1
